version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@mongo:27017
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=4000"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      - VITE_HTTP_ENDPOINT=https://polybank-api.lucasaguiar.live/graphql
      - VITE_WS_ENDPOINT=wss://polybank-api.lucasaguiar.live/graphql
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=5173"

  traefik:
    image: "traefik:v3.0"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  cloudflared-app:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_APP_TOKEN}
    restart: unless-stopped

  cloudflared-api:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_API_TOKEN}
    restart: unless-stopped

volumes:
  mongo-data:
